### ISSUE TITLE
please make a new release

### ISSUE THREAD

**Issue by ygrek** [gmendonca/parallel-ssh#103]
e.g. support for `poll` is important

**Comment by gmendonca** [comment]
Hi, can you explain this better? What you mean by `poll`?

**Comment by ygrek** [comment]
I mean this commit 3158e6054cccdc33c022785bc11e295af96b920d which (supposedly) fixes

```
Traceback (most recent call last):
  File "/usr/bin/parallel-ssh", line 118, in <module>
    do_pssh(hosts, cmdline, opts)
  File "/usr/bin/parallel-ssh", line 89, in do_pssh
    statuses = manager.run()
  File "/usr/lib/python2.7/dist-packages/psshlib/manager.py", line 74, in run
    self.iomap.poll(wait)
  File "/usr/lib/python2.7/dist-packages/psshlib/manager.py", line 242, in poll
    rlist, wlist, _ = select.select(rlist, wlist, [], timeout)
ValueError: filedescriptor out of range in select()
```

with large `-p` values

**Comment by gmendonca** [comment]
Oh, I see. Before moving on, let me clarify some things:
This project is not mine, as stated in the reademe file was exported from https://code.google.com/archive/p/parallel-ssh/ . And unfortunately, the project was discontinued. This was the last version.

I exported to my github because I had some drawbacks when working with this tool, and I decided to work a little bit with it, to see if I can improve.

I'll be happy to have a look on your problem, and see if I can fix it too. I will try the test with large -p values. If possible, can you provide the environment that you running those tests, so I can try to simulate the error just in case?

**Comment by ygrek** [comment]
Nope, I cannot provide the environment. But I can (and will) test it myself to verify the fix when time permits. Anyhow, I will just create debian packages for my internal use, with this ticket I just wanted to make sure that official debian repo will be able to eventually update their pssh package so that these fixes benefit more people in the end.

**Comment by gmendonca** [comment]
Yes, for sure. I'll let this open, so I can work on this too.
